// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/search-bee-species.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { createClient } from "npm:@supabase/supabase-js@^2.97.0";
import { z } from "npm:zod@^4.4.3";
var search_bee_species_default = defineTool({
  name: "search_bee_species",
  title: "Search bee species",
  description: "Search the BeeYield bee species reference (common/scientific name, region, notes).",
  inputSchema: {
    query: z.string().min(1).describe("Free-text search across common name, scientific name, region, notes."),
    limit: z.number().int().min(1).max(50).default(10).describe("Max rows to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }) => {
    const sb = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY);
    const q = `%${query}%`;
    const { data, error } = await sb.from("bee_species").select("common_name,scientific_name,region,size_mm,temperament,honey_yield_kg,notes").or(`common_name.ilike.${q},scientific_name.ilike.${q},region.ilike.${q},notes.ilike.${q}`).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { rows: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/search-bee-diseases.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.97.0";
import { z as z2 } from "npm:zod@^4.4.3";
var search_bee_diseases_default = defineTool2({
  name: "search_bee_diseases",
  title: "Search bee diseases",
  description: "Search the BeeYield bee diseases directory (name, symptoms, cause, treatment).",
  inputSchema: {
    query: z2.string().min(1).describe("Free-text search across disease name, symptoms, cause, cure."),
    limit: z2.number().int().min(1).max(50).default(10)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }) => {
    const sb = createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY);
    const q = `%${query}%`;
    const { data, error } = await sb.from("bee_diseases").select("name,category,severity,symptoms,cause,treatment,prevention,notes").or(`name.ilike.${q},symptoms.ilike.${q},cause.ilike.${q},treatment.ilike.${q}`).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { rows: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/search-florage-plants.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.97.0";
import { z as z3 } from "npm:zod@^4.4.3";
var search_florage_plants_default = defineTool3({
  name: "search_florage_plants",
  title: "Search florage plants",
  description: "Search the BeeYield florage database (bloom windows, nectar & pollen scores).",
  inputSchema: {
    query: z3.string().min(1).describe("Free-text search across plant name, notes."),
    limit: z3.number().int().min(1).max(50).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }) => {
    const sb = createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY);
    const q = `%${query}%`;
    const { data, error } = await sb.from("florage_plants").select("*").or(`common_name.ilike.${q},scientific_name.ilike.${q},notes.ilike.${q}`).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { rows: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/search-knowledge-facts.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.97.0";
import { z as z4 } from "npm:zod@^4.4.3";
var search_knowledge_facts_default = defineTool4({
  name: "search_knowledge_facts",
  title: "Search knowledge base",
  description: "Search the BeeYield knowledge base (facts, sources, confidence).",
  inputSchema: {
    query: z4.string().min(1),
    limit: z4.number().int().min(1).max(50).default(15)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }) => {
    const sb = createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY);
    const q = `%${query}%`;
    const { data, error } = await sb.from("knowledge_facts").select("*").or(`title.ilike.${q},content.ilike.${q},topic.ilike.${q}`).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { rows: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/pollination-stocking-density.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z5 } from "npm:zod@^4.4.3";
var PSI = {
  almond: { colonies_per_acre: 2.5, frames_per_hive: 8, bloom_days: 21 },
  apple: { colonies_per_acre: 1.5, frames_per_hive: 6, bloom_days: 14 },
  avocado: { colonies_per_acre: 2, frames_per_hive: 6, bloom_days: 28 },
  blueberry: { colonies_per_acre: 3, frames_per_hive: 6, bloom_days: 21 },
  cherry: { colonies_per_acre: 2, frames_per_hive: 6, bloom_days: 10 },
  cranberry: { colonies_per_acre: 3, frames_per_hive: 6, bloom_days: 21 },
  cucumber: { colonies_per_acre: 2, frames_per_hive: 5, bloom_days: 45 },
  kiwi: { colonies_per_acre: 4, frames_per_hive: 6, bloom_days: 14 },
  melon: { colonies_per_acre: 1.5, frames_per_hive: 5, bloom_days: 40 },
  pear: { colonies_per_acre: 1.5, frames_per_hive: 6, bloom_days: 12 },
  plum: { colonies_per_acre: 1.5, frames_per_hive: 6, bloom_days: 10 },
  pumpkin: { colonies_per_acre: 1, frames_per_hive: 5, bloom_days: 30 },
  raspberry: { colonies_per_acre: 1.5, frames_per_hive: 6, bloom_days: 28 },
  squash: { colonies_per_acre: 1, frames_per_hive: 5, bloom_days: 35 },
  strawberry: { colonies_per_acre: 1, frames_per_hive: 5, bloom_days: 30 },
  sunflower: { colonies_per_acre: 1, frames_per_hive: 6, bloom_days: 21 },
  watermelon: { colonies_per_acre: 1.5, frames_per_hive: 5, bloom_days: 30 }
};
var pollination_stocking_density_default = defineTool5({
  name: "pollination_stocking_density",
  title: "Pollination stocking density",
  description: "Recommend colonies, frames, and bloom window for a crop and acreage (PSI-based).",
  inputSchema: {
    crop: z5.string().min(1).describe("Crop name (e.g. almond, apple, blueberry)."),
    acres: z5.number().positive().describe("Field size in acres.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ crop, acres }) => {
    const key = crop.toLowerCase().trim();
    const row = PSI[key];
    if (!row) {
      return {
        content: [{ type: "text", text: `Unknown crop "${crop}". Supported: ${Object.keys(PSI).join(", ")}` }],
        isError: true
      };
    }
    const colonies = Math.ceil(row.colonies_per_acre * acres);
    const frames = colonies * row.frames_per_hive;
    const result = {
      crop: key,
      acres,
      recommended_colonies: colonies,
      total_pollination_frames: frames,
      bloom_window_days: row.bloom_days,
      psi_baseline: row.colonies_per_acre
    };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/harvest-estimate.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z6 } from "npm:zod@^4.4.3";
var harvest_estimate_default = defineTool6({
  name: "harvest_estimate",
  title: "Harvest estimate",
  description: "Quick honey harvest estimate: gross, ethical reserve, and apiary total (kg).",
  inputSchema: {
    hives: z6.number().int().positive(),
    frames_per_hive: z6.number().positive().default(8),
    frame_fill_pct: z6.number().min(0).max(100).default(80).describe("Average fill percent per frame."),
    kg_per_full_frame: z6.number().positive().default(2.5),
    hhi: z6.number().min(0).max(100).default(75).describe("Hive Health Index (0-100)."),
    reserve_pct: z6.number().min(0).max(60).default(20).describe("Percent left for colony (ethical reserve).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ hives, frames_per_hive, frame_fill_pct, kg_per_full_frame, hhi, reserve_pct }) => {
    const grossPerHive = frames_per_hive * (frame_fill_pct / 100) * kg_per_full_frame * (hhi / 100);
    const reservePerHive = grossPerHive * (reserve_pct / 100);
    const harvestPerHive = grossPerHive - reservePerHive;
    const apiary = harvestPerHive * hives;
    const out = {
      gross_kg_per_hive: +grossPerHive.toFixed(2),
      reserve_kg_per_hive: +reservePerHive.toFixed(2),
      harvest_kg_per_hive: +harvestPerHive.toFixed(2),
      apiary_harvest_kg: +apiary.toFixed(2),
      hives,
      hhi
    };
    return {
      content: [{ type: "text", text: JSON.stringify(out, null, 2) }],
      structuredContent: out
    };
  }
});

// src/lib/mcp/tools/hive-activity-forecast.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z7 } from "npm:zod@^4.4.3";
function supabaseForUser(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function band(bpm) {
  return bpm < 20 ? "weak" : bpm < 60 ? "normal" : bpm < 120 ? "healthy" : bpm < 250 ? "strong" : "peak";
}
function predict(tempC, windKmh, precipMm, baseline, florage) {
  const tF = tempC < 12 ? 0 : tempC < 18 ? (tempC - 12) / 6 : tempC < 28 ? 1 : tempC < 35 ? 1 - (tempC - 28) * 0.07 : 0.5;
  const wF = windKmh < 8 ? 1 : windKmh < 30 ? 1 - (windKmh - 8) * 0.7 / 22 : 0;
  const pF = precipMm < 0.1 ? 1 : precipMm < 1 ? 0.4 : 0;
  return { bpm: Math.round(baseline * tF * wF * pF * florage), tF, wF, pF };
}
var hive_activity_forecast_default = defineTool7({
  name: "hive_activity_forecast",
  title: "Hive activity & bloom/flight forecast",
  description: "Predicted bees/min plus bloom and flight conditions for a hive over a requested forecast window (default 48 hours). Accepts a hive_id from the user's apiary, or explicit latitude/longitude.",
  inputSchema: {
    hive_id: z7.string().uuid().optional().describe("Hive UUID owned by the signed-in user; supplies coordinates."),
    latitude: z7.number().min(-90).max(90).optional().describe("Used when hive_id is not given."),
    longitude: z7.number().min(-180).max(180).optional(),
    hours: z7.number().int().min(6).max(168).default(48).describe("Forecast window length in hours."),
    baseline_bees_per_min: z7.number().positive().default(100).describe("Colony baseline traffic at ideal conditions."),
    florage_score: z7.number().min(0.3).max(2).default(1).describe("Local forage availability multiplier.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ hive_id, latitude, longitude, hours, baseline_bees_per_min, florage_score }, ctx) => {
    let lat = latitude;
    let lng = longitude;
    let hiveName = null;
    if (hive_id) {
      if (!ctx.isAuthenticated()) {
        return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
      }
      const { data: data2, error } = await supabaseForUser(ctx).from("hives").select("name,latitude,longitude,apiaries(latitude,longitude,name)").eq("id", hive_id).maybeSingle();
      if (error) return { content: [{ type: "text", text: error.message }], isError: true };
      if (!data2) return { content: [{ type: "text", text: `Hive ${hive_id} not found.` }], isError: true };
      const ap = data2.apiaries;
      hiveName = data2.name;
      lat = data2.latitude ?? ap?.latitude ?? lat;
      lng = data2.longitude ?? ap?.longitude ?? lng;
    }
    if (typeof lat !== "number" || typeof lng !== "number") {
      return {
        content: [{ type: "text", text: "Provide latitude and longitude, or a hive_id that has coordinates." }],
        isError: true
      };
    }
    const url = `https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lng}&hourly=temperature_2m,wind_speed_10m,wind_direction_10m,precipitation,relative_humidity_2m&forecast_days=${Math.min(7, Math.ceil(hours / 24) + 1)}&timezone=auto`;
    const res = await fetch(url);
    if (!res.ok) {
      return { content: [{ type: "text", text: `Weather provider error ${res.status}` }], isError: true };
    }
    const data = await res.json();
    const times = data.hourly?.time ?? [];
    const temps = data.hourly?.temperature_2m ?? [];
    const winds = data.hourly?.wind_speed_10m ?? [];
    const dirs = data.hourly?.wind_direction_10m ?? [];
    const precs = data.hourly?.precipitation ?? [];
    const hums = data.hourly?.relative_humidity_2m ?? [];
    const now = Date.now();
    const rows = [];
    for (let i = 0; i < times.length && rows.length < hours; i++) {
      const ts = new Date(times[i]).getTime();
      if (ts < now - 36e5) continue;
      const hour = Number(times[i].slice(11, 13));
      const { bpm, tF, wF, pF } = predict(temps[i], winds[i], precs[i], baseline_bees_per_min, florage_score);
      const daylight = hour >= 7 && hour <= 19;
      const flyable = daylight && tF > 0 && wF > 0 && pF > 0;
      rows.push({
        time: times[i],
        temp_c: temps[i],
        humidity_pct: hums[i],
        wind_kmh: winds[i],
        wind_dir_deg: dirs[i],
        precip_mm: precs[i],
        daylight,
        predicted_bees_per_min: daylight ? bpm : 0,
        band: daylight ? band(bpm) : "night",
        flight_conditions: flyable ? wF > 0.8 && pF === 1 ? "good" : "marginal" : "no-fly",
        // Bloom conditions: nectar secretion favours warm, humid, calm, dry-canopy hours.
        bloom_conditions: temps[i] >= 16 && temps[i] <= 32 && precs[i] < 0.5 && hums[i] >= 40 && hums[i] <= 85 ? "nectar-favourable" : precs[i] >= 0.5 ? "washed-out" : "suppressed"
      });
    }
    const flying = rows.filter((r) => r.flight_conditions !== "no-fly");
    const bloomOk = rows.filter((r) => r.bloom_conditions === "nectar-favourable");
    const peak = rows.reduce(
      (best, r) => r.predicted_bees_per_min > (best?.predicted_bees_per_min ?? -1) ? r : best,
      rows[0]
    );
    const summary = {
      hive_id: hive_id ?? null,
      hive_name: hiveName,
      latitude: lat,
      longitude: lng,
      window_hours: rows.length,
      avg_predicted_bees_per_min: rows.length ? Math.round(rows.reduce((s, r) => s + r.predicted_bees_per_min, 0) / rows.length) : 0,
      peak_predicted_bees_per_min: peak?.predicted_bees_per_min ?? 0,
      peak_time: peak?.time ?? null,
      flyable_hours: flying.length,
      nectar_favourable_hours: bloomOk.length,
      verdict: flying.length === 0 ? "No flight window in this period \u2014 keep colonies fed and unmoved." : bloomOk.length >= rows.length * 0.4 ? "Strong foraging window: good nectar conditions and workable flight hours." : "Mixed conditions: bees can fly, but nectar secretion will be limited.",
      hourly: rows
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "laeifazhrupoqrhqmyzg";
var mcp_default = defineMcp({
  name: "beeyield-mcp",
  title: "BeeYield Apiary Tools",
  version: "0.1.0",
  instructions: "BeeYield tools for AI assistants: search bee species, diseases, florage plants, and the knowledge base; compute recommended pollination stocking density (PSI) and quick honey harvest estimates. All data is read-only and covers Kenyan/EA apiaries.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    search_bee_species_default,
    search_bee_diseases_default,
    search_florage_plants_default,
    search_knowledge_facts_default,
    pollination_stocking_density_default,
    harvest_estimate_default,
    hive_activity_forecast_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
