// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/search-bee-species.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { createClient } from "npm:@supabase/supabase-js@^2.97.0";
import { z } from "npm:zod@^4.4.3";
var search_bee_species_default = defineTool({
  name: "search_bee_species",
  title: "Search bee species",
  description: "Search the BeeYield bee species reference (common/scientific name, region, notes).",
  inputSchema: {
    query: z.string().min(1).describe("Free-text search across common name, scientific name, region, notes."),
    limit: z.number().int().min(1).max(50).default(10).describe("Max rows to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }) => {
    const sb = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY);
    const q = `%${query}%`;
    const { data, error } = await sb.from("bee_species").select("common_name,scientific_name,region,size_mm,temperament,honey_yield_kg,notes").or(`common_name.ilike.${q},scientific_name.ilike.${q},region.ilike.${q},notes.ilike.${q}`).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { rows: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/search-bee-diseases.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.97.0";
import { z as z2 } from "npm:zod@^4.4.3";
var search_bee_diseases_default = defineTool2({
  name: "search_bee_diseases",
  title: "Search bee diseases",
  description: "Search the BeeYield bee diseases directory (name, symptoms, cause, treatment).",
  inputSchema: {
    query: z2.string().min(1).describe("Free-text search across disease name, symptoms, cause, cure."),
    limit: z2.number().int().min(1).max(50).default(10)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }) => {
    const sb = createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY);
    const q = `%${query}%`;
    const { data, error } = await sb.from("bee_diseases").select("name,category,severity,symptoms,cause,treatment,prevention,notes").or(`name.ilike.${q},symptoms.ilike.${q},cause.ilike.${q},treatment.ilike.${q}`).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { rows: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/search-florage-plants.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.97.0";
import { z as z3 } from "npm:zod@^4.4.3";
var search_florage_plants_default = defineTool3({
  name: "search_florage_plants",
  title: "Search florage plants",
  description: "Search the BeeYield florage database (bloom windows, nectar & pollen scores).",
  inputSchema: {
    query: z3.string().min(1).describe("Free-text search across plant name, notes."),
    limit: z3.number().int().min(1).max(50).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }) => {
    const sb = createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY);
    const q = `%${query}%`;
    const { data, error } = await sb.from("florage_plants").select("*").or(`common_name.ilike.${q},scientific_name.ilike.${q},notes.ilike.${q}`).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { rows: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/search-knowledge-facts.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.97.0";
import { z as z4 } from "npm:zod@^4.4.3";
var search_knowledge_facts_default = defineTool4({
  name: "search_knowledge_facts",
  title: "Search knowledge base",
  description: "Search the BeeYield knowledge base (facts, sources, confidence).",
  inputSchema: {
    query: z4.string().min(1),
    limit: z4.number().int().min(1).max(50).default(15)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }) => {
    const sb = createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY);
    const q = `%${query}%`;
    const { data, error } = await sb.from("knowledge_facts").select("*").or(`title.ilike.${q},content.ilike.${q},topic.ilike.${q}`).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { rows: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/pollination-stocking-density.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z5 } from "npm:zod@^4.4.3";
var PSI = {
  almond: { colonies_per_acre: 2.5, frames_per_hive: 8, bloom_days: 21 },
  apple: { colonies_per_acre: 1.5, frames_per_hive: 6, bloom_days: 14 },
  avocado: { colonies_per_acre: 2, frames_per_hive: 6, bloom_days: 28 },
  blueberry: { colonies_per_acre: 3, frames_per_hive: 6, bloom_days: 21 },
  cherry: { colonies_per_acre: 2, frames_per_hive: 6, bloom_days: 10 },
  cranberry: { colonies_per_acre: 3, frames_per_hive: 6, bloom_days: 21 },
  cucumber: { colonies_per_acre: 2, frames_per_hive: 5, bloom_days: 45 },
  kiwi: { colonies_per_acre: 4, frames_per_hive: 6, bloom_days: 14 },
  melon: { colonies_per_acre: 1.5, frames_per_hive: 5, bloom_days: 40 },
  pear: { colonies_per_acre: 1.5, frames_per_hive: 6, bloom_days: 12 },
  plum: { colonies_per_acre: 1.5, frames_per_hive: 6, bloom_days: 10 },
  pumpkin: { colonies_per_acre: 1, frames_per_hive: 5, bloom_days: 30 },
  raspberry: { colonies_per_acre: 1.5, frames_per_hive: 6, bloom_days: 28 },
  squash: { colonies_per_acre: 1, frames_per_hive: 5, bloom_days: 35 },
  strawberry: { colonies_per_acre: 1, frames_per_hive: 5, bloom_days: 30 },
  sunflower: { colonies_per_acre: 1, frames_per_hive: 6, bloom_days: 21 },
  watermelon: { colonies_per_acre: 1.5, frames_per_hive: 5, bloom_days: 30 }
};
var pollination_stocking_density_default = defineTool5({
  name: "pollination_stocking_density",
  title: "Pollination stocking density",
  description: "Recommend colonies, frames, and bloom window for a crop and acreage (PSI-based).",
  inputSchema: {
    crop: z5.string().min(1).describe("Crop name (e.g. almond, apple, blueberry)."),
    acres: z5.number().positive().describe("Field size in acres.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ crop, acres }) => {
    const key = crop.toLowerCase().trim();
    const row = PSI[key];
    if (!row) {
      return {
        content: [{ type: "text", text: `Unknown crop "${crop}". Supported: ${Object.keys(PSI).join(", ")}` }],
        isError: true
      };
    }
    const colonies = Math.ceil(row.colonies_per_acre * acres);
    const frames = colonies * row.frames_per_hive;
    const result = {
      crop: key,
      acres,
      recommended_colonies: colonies,
      total_pollination_frames: frames,
      bloom_window_days: row.bloom_days,
      psi_baseline: row.colonies_per_acre
    };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/harvest-estimate.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z6 } from "npm:zod@^4.4.3";
var harvest_estimate_default = defineTool6({
  name: "harvest_estimate",
  title: "Harvest estimate",
  description: "Quick honey harvest estimate: gross, ethical reserve, and apiary total (kg).",
  inputSchema: {
    hives: z6.number().int().positive(),
    frames_per_hive: z6.number().positive().default(8),
    frame_fill_pct: z6.number().min(0).max(100).default(80).describe("Average fill percent per frame."),
    kg_per_full_frame: z6.number().positive().default(2.5),
    hhi: z6.number().min(0).max(100).default(75).describe("Hive Health Index (0-100)."),
    reserve_pct: z6.number().min(0).max(60).default(20).describe("Percent left for colony (ethical reserve).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ hives, frames_per_hive, frame_fill_pct, kg_per_full_frame, hhi, reserve_pct }) => {
    const grossPerHive = frames_per_hive * (frame_fill_pct / 100) * kg_per_full_frame * (hhi / 100);
    const reservePerHive = grossPerHive * (reserve_pct / 100);
    const harvestPerHive = grossPerHive - reservePerHive;
    const apiary = harvestPerHive * hives;
    const out = {
      gross_kg_per_hive: +grossPerHive.toFixed(2),
      reserve_kg_per_hive: +reservePerHive.toFixed(2),
      harvest_kg_per_hive: +harvestPerHive.toFixed(2),
      apiary_harvest_kg: +apiary.toFixed(2),
      hives,
      hhi
    };
    return {
      content: [{ type: "text", text: JSON.stringify(out, null, 2) }],
      structuredContent: out
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "laeifazhrupoqrhqmyzg";
var mcp_default = defineMcp({
  name: "beeyield-mcp",
  title: "BeeYield Apiary Tools",
  version: "0.1.0",
  instructions: "BeeYield tools for AI assistants: search bee species, diseases, florage plants, and the knowledge base; compute recommended pollination stocking density (PSI) and quick honey harvest estimates. All data is read-only and covers Kenyan/EA apiaries.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    search_bee_species_default,
    search_bee_diseases_default,
    search_florage_plants_default,
    search_knowledge_facts_default,
    pollination_stocking_density_default,
    harvest_estimate_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
